# Generated by Django 3.1.6 on 2021-02-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210222_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitment', models.CharField(blank='universal', max_length=254)),
            ],
        ),
    ]
